[hf CLI] check for updates and notify user

diff --git a/.github/workflows/check-installers.yml b/.github/workflows/check-installers.yml
--- a/.github/workflows/check-installers.yml
+++ b/.github/workflows/check-installers.yml
@@ -36,6 +36,9 @@ jobs:
 
           export PATH="$BIN_DIR:$PATH"
 
+      - name: Check installation
+        shell: bash
+        run: |
           HF_VERSION_PATH="$HF_TEST_ROOT/hf-version.txt"
           hf version | tee "$HF_VERSION_PATH"
           if ! grep -Eq 'huggingface_hub version: [0-9]+(\.[0-9]+){1,2}' "$HF_VERSION_PATH"; then
@@ -48,13 +51,22 @@ jobs:
 
           rm -rf "$HF_TEST_ROOT"
 
+      - name: Check installation method
+        shell: bash
+        run: |
+          hf env
+          if ! hf env | grep -Fq 'Installation method: hf_installer'; then
+            echo "❌ Error: not installed with hf_installer."
+            exit 1
+          fi
+
   windows-installer:
     runs-on: windows-latest
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
 
-      - name: Run installer 
+      - name: Run installer
         shell: pwsh
         run: |
           $hfTestRoot = Join-Path $env:TEMP ([System.Guid]::NewGuid().ToString())
@@ -86,3 +98,12 @@ jobs:
           Remove-Item Env:NO_COLOR
 
           Remove-Item -Path $hfTestRoot -Recurse -Force
+
+      - name: Check installation method
+        shell: pwsh
+        run: |
+          hf env
+          if (-not (hf env | Select-String -SimpleMatch 'Installation method: hf_installer')) {
+            Write-Error "❌ Error: not installed with hf_installer."
+            exit 1
+          }
